---
title: "Data Cleaning"
author: "Loo Wen Wen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(lubridate)
library(tseries)
library(tidyverse)
library(urca)
library(ISLR)
library(pls)
library(glmnet)
attach(Credit)
```


```{r}
fred_data <- read_csv("../data/2025-09-MD.csv")
head(fred_data)
```

```{r}
## Transforms 

transform_1 <- function(x) {
  x
}

# First difference
transform_2 <- function(x) {
  x - lag(x, n = 1, default = NA)
}

# Second difference
transform_3 <- function(x) {
  (x - lag(x, n = 1, default = NA)) - (lag(x, n = 1, default = NA) - lag(x, n = 2, default = NA))
}

# Log transform
transform_4 <- function(x) {
  log(x)
}

# Log first difference
transform_5 <- function(x) {
  log(x) - lag(log(x), n = 1, default = NA)
}

# Log second difference
transform_6 <- function(x) {
  (log(x) - lag(log(x), n = 1, default = NA)) - (lag(log(x), n = 1, default = NA) - lag(log(x), n = 2, default = NA))
}

# Custom ratio transform
transform_7 <- function(x) {
  (x / (lag(x, n = 1, default = NA) - 1)) - (lag(x, n = 1, default = NA) / (lag(x, n = 2, default = NA) - 1))
}

```


```{r}
## Making dataset stationary 

transform_codes <- as.numeric(fred_data[1, ])[-1]
#print(transform_codes)
fred_data_values <- fred_data[-1,]

  print(transform_codes[126])

transforms = list(
  transform_1,
  transform_2,
  transform_3,
  transform_4,
  transform_5,
  transform_6,
  transform_7
)

for (i in 2:length(seq_along(fred_data_values)-1)) {
  #print(i)
  #print(transform_codes[i])
  fn <- transforms[[transform_codes[i-1]]]
  fred_data_values[[i]] <- fn(fred_data_values[[i]])
}


fred_data_clean <- fred_data_values %>%
  mutate(sasdate = mdy(sasdate)) %>%
  filter(sasdate > as.Date("1999-12-31"))

```

```{r}
##Checking for stationarity with ADF Test 

# Normal ADF 
fred_data_clean_adf <- fred_data_clean %>%
  drop_na()

list_of_non_stationary <- list()
for (i in 2:ncol(fred_data_clean_adf)){
  #print(adf.test(fred_data_clean_adf[[i]], k = 0))
  if (adf.test(fred_data_clean_adf[[i]], k = 0)$p.value > 0.05){
    #print(i)
    #print(adf.test(fred_data_clean_adf[[i]]), k = 0)
    list_of_non_stationary <- c(list_of_non_stationary, i)
  }
}


# ADF with Trend 
list_of_non_stationary_trend <- list()
for (i in 2:ncol(fred_data_clean_adf)){
  test_stat = ur.df(fred_data_clean_adf[[i]], type = "trend", lags = 0)@teststat[1]
  critical_val = ur.df(fred_data_clean_adf[[i]], type = "trend", lags = 0)@cval
  if (test_stat > critical_val[2]) {
    #print(critical_val[2])
    #cat(paste("Significant at", significance_levels[j], "level\n"))
    #print(i)
    list_of_non_stationary_trend <- c(list_of_non_stationary_trend, i)
  }
}

print(unlist(list_of_non_stationary_trend))
## Everything is stationary with trend 
print(unlist(list_of_non_stationary))

```
```{r}

```

```{r}
#helper to calc MSE

MSE <- function(pred, truth){ #start and end body of the function by { } - same as a loop 
  return(mean((truth - pred)^2)) #end function with a return(output) statement. Here we can go straight to return because the object of interest is a simple function of inputs
}

y = fred_data_clean$CPIAUCSL

x_cpi <- fred_data_clean[, 107:109]
x_g1_outputincome <- fred_data_clean[, c(2:3, 7:20)]
x_g2_labormkt <- fred_data_clean[, c(21:48, 120:122)]
x_g3_consumptionorders <- fred_data_clean[, 49:58]
x_g4_ordersinv <- fred_data_clean[, c(4:6, 59:64, 123)]
x_g5_moneycredit <- fred_data_clean[, c(65:74, 125:126)]
x_g6_intexrates <- fred_data_clean[, 78:99]
x_g7_prices <- fred_data_clean[, 104:119]
x_g8_stockmkt <- fred_data_clean[, 75:77]
all_used <- c(107:109, 2:3, 7:20, 21:48, 120:122, 49:58, 4:6, 59:64, 123, 65:74, 125:126, 78:99, 104:119, 75:77)
x_other <- fred_data_clean[, -all_used]
```



